


export default class Constants {
    static RHEEL_START = "RHEEL_START"
    static RHEEL_HALF_START = "RHEEL_HALF_START"
    static RHEEL_STOP = "RHEEL_STOP"
    static RHEEL_HALF_STOP = "RHEEL_HALF_STOP"
    static RHEELS_ANIM_STOP = "RHEELS_ANIM_STOP"
    static LINE_ANIM_START = "LINE_ANIM_START"
    static LINE_ANIM_FINISHED = "LINE_ANIM_FINISHED"
    static LINE_ALL_ANIM_FINISHED = "LINE_ALL_ANIM_FINISHED"
    static BONUS_LINE_ALL_ANIM_FINISHED = "BONUS_LINE_ALL_ANIM_FINISHED"
    static BONUS_LINE_ANIM_START = "BONUS_LINE_ANIM_START"
    static BONUS_LINE_ANIM_FINISHED = "BONUS_LINE_ANIM_FINISHED"


    static ICON_ANIM_LOOP = "ICON_ANIM_LOOP"

    static RHEEL_STOP_SIMPLE = "RHEEL_STOP_SIMPLE"
    static RHEEL_STOP_FAST = "RHEEL_STOP_FAST"
    static RHEEL_STOP_CFAST = "RHEEL_STOP_CFAST"
    static RHEEL_STOP_WAIT_BOOK = "RHEEL_STOP_WAIT_BOOK"

    static RHEEL_BONUS_ITEM_COMPLETED = "RHEEL_BONUS_ITEM_COMPLETED"
    static RHEEL_BONUS_ANIM_STARTED = "RHEEL_BONUS_ANIM_STARTED"
}