




class ButtonConstants {
    static BTN_NONAME = "PLAYNGO_BTN_NONAME"


    static BTN_SPIN = "PLAYNGO_BTN_SPIN"
    static BTN_STOP = "PLAYNGO_BTN_STOP"
    static BTN_MAX_BET = "PLAYNGO_BTN_MAX_BET"
    static BTN_PAY_TABLE = "PLAYNGO_BTN_PAY_TABLE"
    static BTN_AUTO_PLAY = "PLAYNGO_BTN_AUTO_PLAY"

    static BTN_LINE_BAR = "PLAYNGO_BTN_LINE_BAR"
    static BTN_LINE_MINUS = "PLAYNGO_BTN_LINE_MINUS"
    static BTN_LINE_PLUS = "PLAYNGO_BTN_LINE_PLUS"
    static BTN_BET_BAR = "PLAYNGO_BTN_BET_BAR"

    static BTN_BET_MINUS = "PLAYNGO_BTN_BET_MINUS"
    static BTN_BET_PLUS = "PLAYNGO_BTN_BET_PLUS"

    static BTN_COIN_CHANGE = "PLAYNGO_BTN_COIN_CHANGE"


    static BTN_COLLECT = "PLAYNGO_BTN_COLLECT"

    static BTN_GAMBLE = "PLAYNGO_BTN_GAMBLE"


    static BTN_GAMBLE_RED = "PLAYNGO_BTN_GAMBLE_RED"
    static BTN_GAMBLE_BLACK = "PLAYNGO_BTN_GAMBLE_BLACK"
    static BTN_GAMBLE_HEART = "PLAYNGO_BTN_GAMBLE_HEART"
    static BTN_GAMBLE_CLUBS = "PLAYNGO_BTN_GAMBLE_CLUBS"
    static BTN_GAMBLE_SPYDE = "PLAYNGO_BTN_GAMBLE_SPYDE"
    static BTN_GAMBLE_DIAMOND = "PLAYNGO_BTN_GAMBLE_DIAMOND"

    static BTN_AUTOPLAY_OK = "PLAYNGO_BTN_AUTOPLAY_OK"
    static BTN_AUTOPLAY_CANCEL = "PLAYNGO_BTN_AUTOPLAY_CANCEL"


    static BTN_STATUSBAR_MENU = "PLAYNGO_BTN_STATUSBAR_MENU"
    static BTN_STATUSBAR_SOUND = "PLAYNGO_BTN_STATUSBAR_SOUND"
    static BTN_STATUSBAR_FAST = "PLAYNGO_BTN_STATUSBAR_FAST"
    static BTN_STATUSBAR_AUTO = "PLAYNGO_BTN_STATUSBAR_AUTO"
    static BTN_STATUSBAR_SPACE = "PLAYNGO_BTN_STATUSBAR_SPACE"
    static BTN_STATUSBAR_LEFT = "PLAYNGO_BTN_STATUSBAR_LEFT"
    static BTN_STATUSBAR_CLOSE = "PLAYNGO_BTN_STATUSBAR_CLOSE"
    static BTN_STATUSBAR_HELP = "PLAYNGO_BTN_STATUSBAR_HELP"
    static BTN_STATUSBAR_MENU_CLOSE = "PLAYNGO_BTN_STATUSBAR_MENU_CLOSE"


    static BTN_UD_COIN_UP = "PLAYNGO_BTN_UD_COIN_UP"
    static BTN_UD_COIN_DOWN = "PLAYNGO_BTN_UD_COIN_DOWN"

    static BTN_UD_COINS_UP = "PLAYNGO_BTN_UD_COINS_UP"
    static BTN_UD_COINS_DOWN = "PLAYNGO_BTN_UD_COINS_DOWN"

    static BTN_UD_COINS_SET = "PLAYNGO_BTN_UD_COINS_SET"
    static BTN_UD_COIN_SET = "PLAYNGO_BTN_UD_COIN_SET"
    static BTN_UD_LINES_SET = "PLAYNGO_BTN_UD_LINES_SET"

    static BTN_UD_LINES_UP = "PLAYNGO_BTN_UD_LINES_UP"
    static BTN_UD_LINES_DOWN = "PLAYNGO_BTN_UD_LINES_DOWN"
    static BTN_MOB_OPEN_CLOSE = "PLAYNGO_BTN_MOB_OPEN_CLOSE"
    static BTN_MOB_OPEN_MENU = "PLAYNGO_BTN_MOB_OPEN_MENU"
    static BTN_MOB_CLOSE_MENU = "PLAYNGO_BTN_MOB_CLOSE_MENU"
}

export default ButtonConstants;
